# Generated by Django 5.0.6 on 2025-04-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('HYGI', 'Hygiene'), ('SELF', 'Self-Care'), ('GOAL', 'Goal-Progress'), ('MISC', 'Miscelaneous')], default='Miscelaneous', max_length=4),
        ),
    ]
