# Generated by Django 5.0.6 on 2025-12-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
